services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    SoftPassio\ApiExceptionBundle\Component\Factory\ResponseFactoryInterface:
        class: '%soft_passio_api_exception.response_factory%'

    SoftPassio\ApiExceptionBundle\Factory\ApiProblemResponseFactory: ~
    SoftPassio\ApiExceptionBundle\Factory\FBExceptionResponseFactory: ~

    SoftPassio\ApiExceptionBundle\EventListener\ApiExceptionSubscriber:
        arguments:
            $debug: '%kernel.debug%'
            $responseFactory: '@SoftPassio\ApiExceptionBundle\Component\Factory\ResponseFactoryInterface'
            $enabled: '%soft_passio_api_exception.enabled%'
            $excludedPaths: '%soft_passio_api_exception.paths_excluded%'

    SoftPassio\ApiExceptionBundle\Factory\ApiProblemFactory:
        arguments:
            $translator: '@translator'
